[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Your Name", email = "you@example.com"},
]
dependencies = []
requires-python = ">=3.10,<3.12"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
